services:
  - type: web
    name: kimstress-iframe-app
    runtime: python
    region: singapore  # Singapore region for better speed
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
